package com.example.accessingdatamysql;

import java.util.Optional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller	// This means that this class is a Controller
@RequestMapping(path="/resv") // This means URL's start with /resv (after Application path)
public class ResvDyController {
	@Autowired // This means to get the bean called tbResvRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private TbResvDyRepository tbResvDyRepository;

	@GetMapping(path="/all")
	public @ResponseBody Iterable<TbResvDy> getAllResvDy() {
		// This returns a JSON or XML with the users
		return tbResvDyRepository.findAll();
	}
}
